/**
 * OrgeYT Soundboard – Sound list
 *
 * Add new sounds with:
 *   name  – display name (shown on the button)
 *   audio – base filename (no extension, no path)
 *
 * Drop the audio file into the sounds/ folder (e.g. my-sound.mp3).
 * Button color is auto-generated from the name.
 */
const SOUNDS = [
  // Original
  { name: "Metal Pipe", audio: "metal-pipe" },
  { name: "Vine Boom", audio: "vine-boom" },
  { name: "Bruh", audio: "bruh" },
  { name: "Fart", audio: "fart" },
  { name: "Error", audio: "error" },
  { name: "Discord Notification", audio: "discord-notification" },
  { name: "Ding", audio: "ding" },
  { name: "Apple Pay", audio: "apple-pay" },
  { name: "Bone Crack", audio: "bone-crack" },
  { name: "Anime Wow", audio: "anime-wow" },
  { name: "SpongeBob Fail", audio: "spongebob-fail" },
  { name: "Taco Bell", audio: "taco-bell" },
  { name: "Dun Dun Dun", audio: "dun-dun-dun" },
  { name: "Rizz", audio: "rizz" },
  { name: "Faah", audio: "faah" },
  { name: "Enrique", audio: "enrique" },
  { name: "Spider-Man", audio: "spider-man" },
  { name: "Air Horn", audio: "air-horn" },
  { name: "What the Dog Doing", audio: "what-the-dog-doing" },
  { name: "Roblox Oof", audio: "roblox-oof" },
  { name: "Wilhelm Scream", audio: "wilhelm-scream" },

  // New batch
  { name: "Discord Leave", audio: "discord-leave" },
  { name: "Yeah Boi", audio: "yeah-boi" },
  { name: "Oh My God", audio: "oh-my-god" },
  { name: "Smoke Detector", audio: "smoke-detector" },
  { name: "Huh", audio: "huh" },
  { name: "Sus Meow", audio: "sus-meow" },
  { name: "Heavenly Music", audio: "heavenly-music" },
  { name: "Galaxy", audio: "galaxy" },
  { name: "A Few Moments Later", audio: "a-few-moments-later" },
  { name: "Censor Beep", audio: "censor-beep" },
  { name: "Gunshot", audio: "gunshot" },
  { name: "Cat Laugh", audio: "cat-laugh" },
  { name: "Wrong Answer", audio: "wrong-answer" },
  { name: "Oh Hell Nah", audio: "oh-hell-nah" },
  { name: "Undertaker Bell", audio: "undertaker-bell" },
  { name: "Camera Shutter", audio: "camera-shutter" },
  { name: "Prowler", audio: "prowler" },
  { name: "Yippee", audio: "yippee" },
  { name: "We'll Be Right Back", audio: "well-be-right-back" },
  { name: "Roblox It's Free", audio: "roblox-its-free" },
  { name: "Skibidi Toilet", audio: "skibidi-toilet" },
  { name: "Quack", audio: "quack" },
  { name: "OrgeYT", audio: "orgeyt" },
  { name: "Bloxy Cola", audio: "bloxy-cola" },
  { name: "Roblox Sword", audio: "roblox-sword" },
  { name: "Oi Oi", audio: "oi-oi" },
  { name: "Mafioso Scream", audio: "mafioso-scream" },
  { name: "Roblox Eating", audio: "roblox-eating" },
  { name: "Roblox Hi", audio: "roblox-hi" },
  { name: "Roblox Screaming Kid", audio: "roblox-screaming-kid" },
  { name: "Roblox Bye", audio: "roblox-bye" },
  { name: "GTA Death", audio: "gta-death" },
  { name: "Bonk", audio: "bonk" },
  { name: "UwU", audio: "uwu" },
  { name: "Among Us Kill", audio: "among-us-kill" },
  { name: "Among Us Role Reveal", audio: "among-us-role-reveal" },
  { name: "Fortnite Death", audio: "fortnite-death" },

  // Meme sounds batch
  { name: "PC Explosion", audio: "pc-explosion" },
  { name: "Anderdingus", audio: "anderdingus" },
  { name: "Asdasd", audio: "asdasd" },
  { name: "Autotune Laugh", audio: "autotune-laugh" },
  { name: "Back Up", audio: "back-up" },
  { name: "Bad to the Bone", audio: "bad-to-the-bone" },
  { name: "Ben Hohohoh", audio: "ben-hohohoh" },
  { name: "Bing Chilling", audio: "bing-chilling" },
  { name: "Car Crash", audio: "car-crash" },
  { name: "Cat iPhone Ringtone", audio: "cat-iphone-ringtone" },
  { name: "Cha Ching Money", audio: "cha-ching-money" },
  { name: "Clapping", audio: "clapping" },
  { name: "Concrete Scrape", audio: "concrete-scrape" },
  { name: "Confetti Pop", audio: "confetti-pop" },
  { name: "Downer Noise", audio: "downer-noise" },
  { name: "Explosion Meme", audio: "explosion-meme" },
  { name: "Fart with Reverb", audio: "fart-with-reverb" },
  { name: "Gop Gop Gop", audio: "gopgopgop" },
  { name: "GTA Ah Shit", audio: "gta-ah-shit" },
  { name: "I Farted", audio: "i-farted" },
  { name: "I Like Ya Cut G", audio: "i-like-ya-cut-g" },
  { name: "Kids Saying Yay", audio: "kids-saying-yay" },
  { name: "Lack of a Father Figure", audio: "lack-of-a-father-figure" },
  { name: "Laugh", audio: "laugh" },
  { name: "Long Brain Fart", audio: "long-brain-fart" },
  { name: "Man Snoring", audio: "man-snoring" },
  { name: "Michael Don't Leave Me Here", audio: "michael-dont-leave-me-here" },
  { name: "Minecraft Explosion", audio: "minecraft-explosion" },
  { name: "Nanannonono", audio: "nanannonono" },
  { name: "No No Wait Wait", audio: "no-no-wait-wait" },
  { name: "Nope", audio: "nope" },
  { name: "Notification", audio: "notification" },
  { name: "Oh No No No No Laugh", audio: "oh-no-no-no-no-laugh" },
  { name: "Oh No No No TikTok", audio: "oh-no-no-no-tiktok" },
  { name: "Oi Oi Oe", audio: "oi-oi-oe" },
  { name: "Pluh", audio: "pluh" },
  { name: "Raaar", audio: "raaar" },
  { name: "Roblox Explosion", audio: "roblox-explosion" },
  { name: "Sad Meow Song", audio: "sad-meow-song" },
  { name: "Scream", audio: "scream" },
  { name: "Shut Your Mouth", audio: "shut-your-mouth" },
  { name: "Studio Audience Awwww", audio: "studio-audience-awwww" },
  { name: "Take Off", audio: "take-off" },
  { name: "Talking Ben Ugh", audio: "talking-ben-ugh" },
  { name: "Talking Ben Yes", audio: "talking-ben-yes" },
  { name: "Talking Ben No", audio: "talking-ben-no" },
  { name: "You're Fine", audio: "youre-fine" },
  { name: "Undertale Game Over", audio: "undertale-gameover" },
  { name: "Weeeee", audio: "weeeee" },
  { name: "Yeahoo", audio: "yeahoo" },
  { name: "Yes Lara", audio: "yes-lara" },
  { name: "Your Phone Ringing", audio: "your-phone-ringing" }
];
