export default [
  { name: "Snow", hex: "#FFFAFA" },
  { name: "Ghost White", hex: "#F8F8FF" },
  { name: "White", hex: "#FFFFFF" },
  { name: "Ivory", hex: "#FFFFF0" },
  { name: "Floral White", hex: "#FFFAF0" },
  { name: "Antique White", hex: "#FAEBD7" },
  { name: "Linen", hex: "#FAF0E6" },
  { name: "Seashell", hex: "#FFF5EE" },
  { name: "Old Lace", hex: "#FDF5E6" },
  { name: "Black", hex: "#000000" },
  { name: "Charcoal", hex: "#333333" },
  { name: "Dim Gray", hex: "#696969" },
  { name: "Grey", hex: "#8E8E93" },
  { name: "Light Gray", hex: "#D3D3D3" },
  { name: "Silver", hex: "#C0C0C0" },
  { name: "Gainsboro", hex: "#DCDCDC" },
  { name: "Red", hex: "#FF3B30" },
  { name: "Crimson", hex: "#DC143C" },
  { name: "Firebrick", hex: "#B22222" },
  { name: "Maroon", hex: "#800000" },
  { name: "Salmon", hex: "#FA8072" },
  { name: "Tomato", hex: "#FF6347" },
  { name: "Orange", hex: "#FF9500" },
  { name: "Dark Orange", hex: "#FF8C00" },
  { name: "Coral", hex: "#FF7F50" },
  { name: "Peach", hex: "#FFB07C" },
  { name: "Gold", hex: "#FFD700" },
  { name: "Yellow", hex: "#FFCC00" },
  { name: "Khaki", hex: "#F0E68C" },
  { name: "Olive", hex: "#708238" },
  { name: "Lime", hex: "#A3E635" },
  { name: "Chartreuse", hex: "#7FFF00" },
  { name: "Green", hex: "#34C759" },
  { name: "Forest Green", hex: "#228B22" },
  { name: "Mint", hex: "#98FF98" },
  { name: "Turquoise", hex: "#40E0D0" },
  { name: "Teal", hex: "#008080" },
  { name: "Cyan", hex: "#32ADE6" },
  { name: "Blue", hex: "#007AFF" },
  { name: "Navy", hex: "#0A2540" },
  { name: "Royal Blue", hex: "#4169E1" },
  { name: "Sky Blue", hex: "#87CEEB" },
  { name: "Purple", hex: "#AF52DE" },
  { name: "Lavender", hex: "#B57EDC" },
  { name: "Plum", hex: "#5C2E5C" },
  { name: "Magenta", hex: "#FF00FF" },
  { name: "Pink", hex: "#FF2D55" },
  { name: "Hot Pink", hex: "#FF69B4" },
  { name: "Rose", hex: "#FF007F" },
  { name: "Brown", hex: "#A16A38" },
  { name: "Sienna", hex: "#A0522D" },
  { name: "Beige", hex: "#F5F5DC" },
  { name: "Tan", hex: "#D2B48C" },
  { name: "Chocolate", hex: "#D2691E" },
  { name: "Peru", hex: "#CD853F" },
  { name: "Slate", hex: "#708090" },
  { name: "Indigo", hex: "#4B0082" },
  { name: "Turquoise Blue", hex: "#00CED1" },
  { name: "Mint Cream", hex: "#F5FFFA" },
  { name: "Honeydew", hex: "#F0FFF0" },
  { name: "Azure", hex: "#F0FFFF" },
  { name: "Alice Blue", hex: "#F0F8FF" },
    { name: "Dark Red", hex: "#8B0000" },
  { name: "Indian Red", hex: "#CD5C5C" },
  { name: "Light Coral", hex: "#F08080" },
  { name: "Deep Pink", hex: "#FF1493" },
  { name: "Light Pink", hex: "#FFB6C1" },
  { name: "Pale Violet Red", hex: "#DB7093" },

  { name: "Orange Red", hex: "#FF4500" },
  { name: "Dark Salmon", hex: "#E9967A" },
  { name: "Light Salmon", hex: "#FFA07A" },
  { name: "Sandy Brown", hex: "#F4A460" },
  { name: "Burlywood", hex: "#DEB887" },

  { name: "Goldenrod", hex: "#DAA520" },
  { name: "Dark Goldenrod", hex: "#B8860B" },
  { name: "Light Goldenrod Yellow", hex: "#FAFAD2" },
  { name: "Lemon Chiffon", hex: "#FFFACD" },
  { name: "Cornsilk", hex: "#FFF8DC" },

  { name: "Dark Olive Green", hex: "#556B2F" },
  { name: "Yellow Green", hex: "#9ACD32" },
  { name: "Lawn Green", hex: "#7CFC00" },
  { name: "Spring Green", hex: "#00FF7F" },
  { name: "Sea Green", hex: "#2E8B57" },
  { name: "Dark Green", hex: "#006400" },
  { name: "Pale Green", hex: "#98FB98" },

  { name: "Aquamarine", hex: "#7FFFD4" },
  { name: "Medium Turquoise", hex: "#48D1CC" },
  { name: "Dark Turquoise", hex: "#00CED1" },
  { name: "Light Sea Green", hex: "#20B2AA" },

  { name: "Deep Sky Blue", hex: "#00BFFF" },
  { name: "Dodger Blue", hex: "#1E90FF" },
  { name: "Steel Blue", hex: "#4682B4" },
  { name: "Light Blue", hex: "#ADD8E6" },
  { name: "Powder Blue", hex: "#B0E0E6" },
  { name: "Cadet Blue", hex: "#5F9EA0" },

  { name: "Midnight Blue", hex: "#191970" },
  { name: "Cornflower Blue", hex: "#6495ED" },
  { name: "Medium Blue", hex: "#0000CD" },
  { name: "Dark Blue", hex: "#00008B" },

  { name: "Blue Violet", hex: "#8A2BE2" },
  { name: "Medium Purple", hex: "#9370DB" },
  { name: "Dark Violet", hex: "#9400D3" },
  { name: "Dark Orchid", hex: "#9932CC" },
  { name: "Medium Orchid", hex: "#BA55D3" },
  { name: "Thistle", hex: "#D8BFD8" },

  { name: "Moccasin", hex: "#FFE4B5" },
  { name: "Navajo White", hex: "#FFDEAD" },
  { name: "Bisque", hex: "#FFE4C4" },
  { name: "Blanched Almond", hex: "#FFEBCD" },
  { name: "Wheat", hex: "#F5DEB3" },

  { name: "Saddle Brown", hex: "#8B4513" },
  { name: "Dark Brown", hex: "#654321" },
  { name: "Rosy Brown", hex: "#BC8F8F" },

  { name: "Light Slate Gray", hex: "#778899" },
  { name: "Dark Slate Gray", hex: "#2F4F4F" },
  { name: "Dark Gray", hex: "#A9A9A9" },

  { name: "Smoke", hex: "#F5F5F5" },
  { name: "White Smoke", hex: "#F5F5F5" },
  { name: "Cream", hex: "#FFFDD0" },

  { name: "Neon Green", hex: "#39FF14" },
  { name: "Neon Blue", hex: "#4D4DFF" },
  { name: "Neon Pink", hex: "#FF10F0" },
  { name: "Neon Purple", hex: "#BC13FE" },
  { name: "Neon Orange", hex: "#FF5F1F" },

  { name: "Discord Blurple", hex: "#5865F2" },
  { name: "Roblox Red", hex: "#E2231A" },
  { name: "Scratch Orange", hex: "#FF8C1A" },
  { name: "YouTube Red", hex: "#FF0000" },
  { name: "Minecraft Grass", hex: "#5C913B" }
];